# Generated by Django 6.0.2 on 2026-04-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la entidad patrocinadora', max_length=200, unique=True)),
                ('siglas', models.CharField(help_text='Siglas de la entidad (máx. 20 caracteres)', max_length=20, unique=True)),
                ('direccion', models.CharField(help_text='Dirección completa (única por entidad)', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del municipio (único)', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la provincia (único)', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la temática (único)', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Temática',
                'verbose_name_plural': 'Temáticas',
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador o nombre del tribunal', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunales',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del evento (único)', max_length=200, unique=True)),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('id_entidad', models.ForeignKey(help_text='Entidad que patrocina el evento', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='evento_app.entidad')),
            ],
        ),
        migrations.AddField(
            model_name='entidad',
            name='id_municipio',
            field=models.ForeignKey(help_text='Municipio donde se ubica la entidad', on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='evento_app.municipio'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre(s)', max_length=100)),
                ('apellido1', models.CharField(help_text='Primer apellido', max_length=100)),
                ('apellido2', models.CharField(blank=True, help_text='Segundo apellido', max_length=100)),
                ('grado_cientifico', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_app.evento')),
                ('id_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_app.participante')),
            ],
            options={
                'unique_together': {('id_evento', 'id_participante')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos', through='evento_app.EventoParticipante', to='evento_app.participante'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='evento_app.provincia'),
        ),
        migrations.CreateModel(
            name='EventoTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_app.evento')),
                ('id_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_app.tematica')),
            ],
            options={
                'verbose_name': 'Evento temática',
                'verbose_name_plural': 'Evento temáticas',
                'unique_together': {('id_evento', 'id_tematica')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='tematicas',
            field=models.ManyToManyField(related_name='eventos', through='evento_app.EventoTematica', to='evento_app.tematica'),
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del trabajo (único)', max_length=300, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='evento_app.evento')),
                ('id_participante', models.OneToOneField(help_text='Participante autor (único por trabajo)', on_delete=django.db.models.deletion.CASCADE, related_name='trabajo', to='evento_app.participante')),
                ('id_tematica', models.ForeignKey(help_text='Temática asociada', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='evento_app.tematica')),
                ('id_tribunal', models.ForeignKey(help_text='Tribunal encargado de revisar el trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='evento_app.tribunal')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoAprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField(default=False, help_text='Indica si el pago fue realizado')),
                ('ruta_documento', models.CharField(help_text='Ruta del archivo PowerPoint de la presentación aprobada', max_length=500, unique=True)),
                ('id_trabajo', models.OneToOneField(help_text='Trabajo aprobado (relación uno a uno)', on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion', to='evento_app.trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo aprobado',
                'verbose_name_plural': 'Trabajos aprobados',
            },
        ),
        migrations.CreateModel(
            name='Oponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre(s)', max_length=100)),
                ('apellido1', models.CharField(help_text='Primer apellido', max_length=100)),
                ('apellido2', models.CharField(blank=True, help_text='Segundo apellido', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oponente_profile', to=settings.AUTH_USER_MODEL)),
                ('id_tribunal', models.ForeignKey(help_text='Tribunal al que pertenece el oponente', on_delete=django.db.models.deletion.PROTECT, related_name='oponentes', to='evento_app.tribunal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VersionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_numero', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to='trabajos/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('tamanio', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='evento_app.trabajo')),
            ],
            options={
                'ordering': ['-version_numero'],
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_conformidad', models.TextField(help_text='Descripción de la no conformidad')),
                ('id_version_trabajo', models.OneToOneField(help_text='Versión del trabajo que presenta no conformidad', on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidad', to='evento_app.versiontrabajo')),
            ],
            options={
                'verbose_name': 'No conformidad',
                'verbose_name_plural': 'No conformidades',
            },
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__gt', models.F('fecha_apertura'))), name='fecha_cierre_posterior_a_apertura'),
        ),
        migrations.AlterUniqueTogether(
            name='versiontrabajo',
            unique_together={('trabajo', 'version_numero')},
        ),
    ]
