# Generated by Django 6.0.2 on 2026-05-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versiontrabajo',
            options={'ordering': ['-version_numero'], 'verbose_name': 'Versión de trabajo', 'verbose_name_plural': 'Versiones de trabajo'},
        ),
        migrations.AlterField(
            model_name='noconformidad',
            name='id_version_trabajo',
            field=models.ForeignKey(help_text='Versión del trabajo que presenta no conformidad', on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidades', to='evento_app.versiontrabajo'),
        ),
        migrations.AlterField(
            model_name='versiontrabajo',
            name='tamanio',
            field=models.PositiveIntegerField(verbose_name='Tamaño (KB)'),
        ),
    ]
