# Generated by Django 6.0.2 on 2026-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0002_alter_versiontrabajo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajoaprobado',
            name='ruta_documento',
        ),
        migrations.AddField(
            model_name='trabajoaprobado',
            name='documento',
            field=models.FileField(blank=True, help_text='Archivo PowerPoint del trabajo aprobado', null=True, upload_to='presentaciones/%Y/%m/%d/'),
        ),
    ]
